/***********************************************************************************************
** Program name: Project 3
** Author: Jordan Hamilton
** Date: 11/4/2018
** Description: This fantasy fighter game
***********************************************************************************************/

#include "Menu.hpp"
#include "Game.hpp"

/***********************************************************************************************
** Description: This program can be run via the project3 executable generated by make.
***********************************************************************************************/
int main() {

  Menu mainMenu, gameMenu;

  mainMenu.addMenuItem("Play a game");
  mainMenu.addMenuItem("Exit");

  gameMenu.addMenuItem("Barbarian");
  gameMenu.addMenuItem("Blue Men");
  gameMenu.addMenuItem("Harry Potter");
  gameMenu.addMenuItem("Medusa");
  gameMenu.addMenuItem("Vampire");

  do {
    int character1 = gameMenu.getIntChoiceFromPrompt("Who should fighter 1 be?", 1, gameMenu.getMenuChoices(), true);
    int character2 = gameMenu.getIntChoiceFromPrompt("Who should fighter 2 be?", 1, gameMenu.getMenuChoices(), true);
    Game newGame(character1, character2);

  } while (mainMenu.getIntChoiceFromPrompt(1, mainMenu.getMenuChoices(), true) != 2);

  return 0;

}
